/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame2.java
 *
 * Created on Oct 13, 2011, 5:26:16 PM
 */

package multiplerouting;
import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.*;
import java.lang.*;
import java.lang.String;
import java.awt.Button;
import javax.swing.*;
import java.sql.*;
import java.lang.String;
import java.util.ArrayList;

/**
 *
 * @author madhu
 */
public class NewJFrame2 extends javax.swing.JFrame {
//Statement stmt;


    /** Creates new form NewJFrame2 */
    public NewJFrame2() {
        initComponents();
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 0));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Papyrus", 3, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 102, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("                This is a demo Multiple Routing Configurations for Fast\nIP Network Recovery model created using Netbeans IDE(Version 6.9.1) and \nJava Development Kit(JDK)1.6\nThis software may be freely distributed, copied, modified by the\nusers. \n\t\t\n       This software is submitted as our MINI project in VITAE.\n\t\t\n\tWe sincerely thank our instructor B.PHIJIK sirfor his valuable\n cooperation and guidance.\n\n\t\t\tYours sincerely\n\t\t\t(Team Members)\n\t\t\tP.MADHUKAR REDDY(08uq1a0501)\t\n\t\t\tD.JUGAL KISHORE(08uq1a0503)\t\t\t\tR.NITIN KIMAR REDDY(08uq1a0519)\n\t\t\tB.VIKAS TEJA(08uq1a0533)");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       NewJFrame frame1= new NewJFrame();
     NewJFrame2 frame2=new NewJFrame2();

     frame2.setVisible(false);
       frame1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public int count()
   {
   Connection con2;
   Statement ps;
    // ResultSet rs;
   try
   {
Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
con2 = DriverManager.getConnection("jdbc:odbc:project","sa","password");
   // ps=con2.prepareStatement("select count(*) from node_details");
ps=con2.createStatement();

    ResultSet rs=ps.executeQuery("select count(*) from node_details");

    if(rs.next()==true)
    {
        count1 = rs.getInt(1);
       System.out.println(rs.getInt(1));
   
       }
    rs.close();
     ps.close();
    con2.close();

    }

   catch(Exception e)
         {
             System.out.println( "error" +e);
         }
    return(count1);

}
public String path(String a)
    {
    Connection con1;
    PreparedStatement ps1;
   // ResultSet rs1=null;
    try{
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
	con1= DriverManager.getConnection("jdbc:odbc:project","sa","password");
     ps1=con1.prepareStatement("select node2 from weights where weight=(select min(weight)from weights where node1='?')");
     ps1.setString(1,a);
     ResultSet rs1=ps1.executeQuery();
     if(rs1.first()==true)
     System.out.println(rs1.getString(1));
     temp=rs1.getString(1);
//rs1.close();
//ps1.close();

        }
    catch(Exception e)
         {
        e.printStackTrace();
             System.out.println( "error" +e);
         }
return(temp);


}
public int count1;
 public String temp;
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
